name: Setup wit-bindgen
description: 👨‍💻 Install the wit-bindgen CLI for GitHub Actions

branding:
  icon: play
  color: blue

inputs:
  wit-bindgen-version:
    description: Which version of wit-bindgen to install. This can be an exact version specifier such as '0.16.0' or a semver range like '~0.16.0' or '0.x'. Use 'latest' to always install the latest release. Defaults to 'latest'.
    default: latest
  wit-bindgen-token:
    description: The GitHub token to use when fetching the version list from bytecodealliance/wit-bindgen. You shouldn't have to touch this. The default is the 'github.token' if you're on github.com or unauthenticated (rate limited) if you're not on github.com.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  wit-bindgen-version:
    description: The version of wit-bindgen that was installed. This will be something like '0.16.0 or similar.
  cache-hit:
    description: Whether or not wit-bindgen was restored from the runner's cache or download anew.

runs:
  using: node20
  main: dist/main.js
